### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/jigsaws/jigsaws_annot/Suturing/meta_file_Suturing.txt'

### ISSUE THREAD

**Issue by HappyStupidChild** [shinkyo0513/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation#3]
Traceback (most recent call last):
  File "main_jigsaws_group.py", line 431, in <module>
    _, rhos[i], l1s[i] = train(args, split_id, device, save_label)
  File "main_jigsaws_group.py", line 88, in train
    video_datasets = {x: SkillVideoDataset(ds_root, x=='train', task=args.task, debug=args.debug,
  File "main_jigsaws_group.py", line 88, in <dictcomp>
    video_datasets = {x: SkillVideoDataset(ds_root, x=='train', task=args.task, debug=args.debug,
  File "/root/autodl-tmp/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation/dataset/skill_video_dataset.py", line 56, in __init__
    self.video_info_dict = self.__read_video_info()
  File "/root/autodl-tmp/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation/dataset/skill_video_dataset.py", line 147, in __read_video_info
    return self.__read_taskwise_video_info(self.task)
  File "/root/autodl-tmp/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation/dataset/skill_video_dataset.py", line 86, in __read_taskwise_video_info
    skill_annot_file = open(skill_annot_dir, 'r')
FileNotFoundError: [Errno 2] No such file or directory: './data/jigsaws/jigsaws_annot/Suturing/meta_file_Suturing.txt'

**Comment by HappyStupidChild** [comment]
> Traceback (most recent call last): File "main_jigsaws_group.py", line 431, in _, rhos[i], l1s[i] = train(args, split_id, device, save_label) File "main_jigsaws_group.py", line 88, in train video_datasets = {x: SkillVideoDataset(ds_root, x=='train', task=args.task, debug=args.debug, File "main_jigsaws_group.py", line 88, in video_datasets = {x: SkillVideoDataset(ds_root, x=='train', task=args.task, debug=args.debug, File "/root/autodl-tmp/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation/dataset/skill_video_dataset.py", line 56, in **init** self.video_info_dict = self.__read_video_info() File "/root/autodl-tmp/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation/dataset/skill_video_dataset.py", line 147, in __read_video_info return self.__read_taskwise_video_info(self.task) File "/root/autodl-tmp/Surgical-Skill-Assessment-via-Video-Semantic-Aggregation/dataset/skill_video_dataset.py", line 86, in __read_taskwise_video_info skill_annot_file = open(skill_annot_dir, 'r') FileNotFoundError: [Errno 2] No such file or directory: './data/jigsaws/jigsaws_annot/Suturing/meta_file_Suturing.txt'

可不可以在数据处理部分，提供相关说明。

**Comment by Mp991004** [comment]
这个文件JIGSAWS官网有提供

**Comment by Fan2022HNU** [comment]
我也遇到相同的问题

**Comment by qwerryfiwy** [comment]
parts = line.strip().split()
if len(parts) < 3: 
    continue

video_name = parts[0]
spc = parts[1]        # e.g., 'N' (Novice)
grs = int(parts[2])   # e.g., 13 (Global Score)
ele_scores = [int(x) for x in parts[3:]] # The rest are element scores

skill_annot_dict[video_name] = [spc, grs] + ele_scores

We can do it right?
